# Generated by Django 2.0.7 on 2018-07-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180718_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='road.Road'),
        ),
    ]
