# Generated by Django 2.0.7 on 2018-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_auto_20180714_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='situation',
        ),
        migrations.AddField(
            model_name='road',
            name='speed',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='isimpassable',
            field=models.NullBooleanField(),
        ),
    ]
