# Generated by Django 2.0.7 on 2018-07-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0003_auto_20180715_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='isimpassable',
            field=models.BooleanField(),
        ),
    ]
