# Generated by Django 2.0.7 on 2018-07-18 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0008_auto_20180717_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
