# Generated by Django 2.0.7 on 2018-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin',
            field=models.SmallIntegerField(null=True),
        ),
    ]
