# Generated by Django 2.0.7 on 2018-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
