# Generated by Django 2.0.7 on 2018-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20180816_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalcar',
            name='location',
            field=models.CharField(default='', max_length=140),
        ),
    ]
