# Generated by Django 2.0.7 on 2018-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_criminalcar_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalcar',
            name='creator',
            field=models.CharField(default='', max_length=140),
        ),
    ]
