# Generated by Django 2.0.7 on 2018-08-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_criminalcar_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalcar',
            name='creator',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='criminalcar',
            name='location',
            field=models.CharField(default='', max_length=140, null=True),
        ),
    ]
