# Generated by Django 2.0.7 on 2018-08-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20180827_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='message',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
