# Generated by Django 2.0.7 on 2018-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_car_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('number', models.CharField(max_length=140)),
                ('owner', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
